config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  get 'home/about'
  root 'home#index'
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<html>
<head>
  

  <title>SDR Resume</title>
  	<meta name="description" content="SDR Resume. Check out my work history.">
  	<link rel="stylesheet" media="screen, print" href="/style.css">
  	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>


	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="#">Santo DeRose</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      >
      
     <li class="nav-item">
       <%= link_to "Back To Resume", root_path %>
        </li>
    </ul>
    
  </div>
</nav>

<div class="card">
  <div class="card-header">
    <h5><center>IT PROJECT MANAGER COVER LETTER</center></h5>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Dear Hiring Manager,
</br></br>
With 20+ years of experience in leading large-scale technology releases and change management projects for well-established organizations, I look forward to bringing my exceptional leadership skills to the IT Project Manager opening at your company.</br>
</br>
From planning project operations and managing client communication to allocating resources and completing milestones, I’m adept in my ability to lead teams and achieve on-time and under-budget project implementation. In my current role as IT Project Manager for DELL EMC, I lead a team of 20+ IT professionals to successfully manage 12+ major technology releases per year. 
</br></br>
I’m confident that my strengths in capacity planning, product implementation, continuous improvement, and change management will help your company deliver successful projects and exceed client expectations. I would greatly appreciate the opportunity to meet with you and discuss my qualifications and your requirements in detail. Thank you for your consideration, and I look forward to speaking with you soon.
 </br></br>
 
Sincerely,
</br>
Santo DeRose
</p>
    </blockquote>
  </div>
</div>
<center>
 <h1></h1>
 <p></p>
 <img src="" height="" width=""></br>
 <a href=""></a></br>
 <a href="http://www.linkedin.com/in/santo-derose-342ab39" target="new">Linkedin Profile!!</a>
</center>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

app/views/home/index.html.erb
<html>
<head>
  

  <title>SDR Resume</title>
  	<meta name="description" content="SDR Resume. Check out my work history.">
  	<link rel="stylesheet" media="screen, print" href="/style.css">
  	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <a class="navbar-brand" href="#">Santo DeRose</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      
      
    
      
    <li class="nav-item">
        <%= link_to "Cover Letter", home_about_path, class: "nav-link" %>
        </li>
     
    </ul>
    
  </div>
</nav>
<div class="card">
  <div class="card-header">
    <center><h1>INFRASTRUCTURE PROJECT MANAGER</h1></center>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><h3><center>Project Management • Enterprise Implementations • Project Management • System Engineering
• Scrum Master</center></h3>

Diligent Senior IT Specialist offering a proven record of success managing all phases of technology project implementations throughout the project lifestyle, contributing expertise in EMC storage system.  Foster client relationships, lead teams, communicate, and collaborate across functions and with all levels to produce high-quality deliverables that meet or exceed timeline, achieve customer objectives, maximize performance, and improve processes.  Major clients include JPMC, Microsoft, Cargill, Citadel, Northwestern Hospital, Ingram Micro, Ensono, and TCS.<br/> <br/>

<strong>Skills summary:</strong><br/>

                      <h5><center>Value-Added Leadership</center></h5>

Cross- Functional Supervision • Team Building & Mentoring • Client Relations & Presentations 
• Business & IT Planning • Vendor Management

<h5><center>IT Project Lifecycle</center></h5>
Requirements Analysis • Costing & Budgeting • Project Charter • Project Planning • Project Scheduling • Scrum Master • Ruby on Rails • NodeJS • Yarn • Git • Sublime • Bootstrap •  
Heroku • Github • RubyGems • CSS • Bootstrap • HTML•  Project Monitoring • Project Closing<br/>

<h5><center>Project Management</center></h5>
Enterprise Implementations • System Migrations • Disaster Recovery • Inventory Management 
• Verification and testing • Planning and coordination • Invoice generation • POC Testing
AWS / Migrations / Architecture • Google Cloud Migrations • vSphere • ESXi
Microsoft Project
<br/>

<h5><center>Technical Skills</center></h5>
VMAX • VMAX3 • PowerMax • Brocade • Cisco • Isilon • ExtremeIO • ECS • SRDF • VXRAIL / VRACK / CLOUD
Data Domain • DLM • IDPA • Windows • Linux • HP-UX • IBMi • AIX • Sun Solaris • IBM Mainframe 
AWS / Migrations / Architecture • Google Cloud Migrations • vSphere • ESXi

</p>
      
    </blockquote>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <strong><center>EXPERIENCE
DELL EMC CORPORATION, Lisle, IL							07/2000 to 09/2020
PROJECT MANAGEMENT</strong></center>

  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><strong><center>PROJECT MANAGEMENT</center></strong>	 
•	Collaborated with team members to deliver project requirements, develop solutions and meet deadlines.<br/>
•	Communicated with data architects, programmers, engineers, and vendors to keep projects on track.<br/>
•	Executed Customer Data Center Installations, Upgrades, Configurations Of Storage Systems Including SAN Networking Systems.<br/>
•	Resolved technical issues encountered during Implementation related to infrastructure management, Security compliance, and SLA terms. Liaised with customer management team, end user.<br/>
•	Implemented best practices in the SAN Infrastructure for Enterprise and Midrange customers achieving a customer satisfaction rating of 95% or higher.<br/>
•	Managed clients to upgrade to target code levels, migrate to the latest version of management applications, resolve business-critical application issues, and reduce downtime.<br/>
•	Achieved zero-defect implementations resulting in a reduction of miscellaneous trouble ticket creation.<br/>
•	Delivered accurate solutions to major Financial Institutions while adhering to strict service level agreements.<br/>
•	Identified new defects to the engineering team to improve microcode, minimizing Customer impact.<br/>
•	Enforced SRDF procedures to maintain overall data integrity.<br/>
•	Defined processes and tools best suited to each project. Created project road maps, plans, schedules and work breakdown structures.<br/>
</p>
      
    </blockquote>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <strong><center>PROJECT MANAGEMENT of DATA MIGRATIONS</center></strong>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>• Manage end-to-end complex data migration, conversion and data modeling.
• Participate in quality management reviews as outlined in the Verification and Validation Overview.<br/>
• Support deployment of solution, cut over planning and execution activities.
•Define the migration strategy and plan.<br/>
•Developing and delivering a details data migration plan.
• Managing a small team.<br/>
• Managing the data and reporting analysis.<br/>
• Overseeing and ensuring delivery of all aspects of data analysis, mapping and transfer.
• Liasing with key stakeholders and system integration partners.<br/>
• Identifying the data migration impact of all proposed changes.<br/>
• Owning the quality of the migrated data and the validity of the migration processes and operation.<br/>
• Manage data migration workstream within the established project budgets and advise Project.<br/>
• Provide timely status reporting to all stakeholders.<br/>
• Interpret and complete vendor provided data migration workbooks.<br/>
•As part of the project closure, evaluate and make recommendations for future improvements.<br/>
• Highly effective working in a team, as well as working independently.
• Major clients include JPMC, Microsoft, Cargill, Illinois State Tollway, State of Illinois, Kemper.<br/>
• Manage end-to-end  Data Center Migrations of Enterprise EMC Storage Systems. Open System and IBM Mainframe Host Migrations. Including (SRDF) Disaster Recovery Migrations and Testing. <br/>    
</p>
      
    </blockquote>
  </div>
</div>
<div class="card">
  <div class="card-header">
    <strong><center>PROJECT MANAGER/SCRUM MASTER</center></strong>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>I was the PS team lead at my last position at EMC. I used my leadership skills  to convince senior management to apply AgileScrum to the PS organization. I lead the Agile Scrum implementation and started putting in practice the core principles of Agile into the projects. This was a rare opportunity to transform it into a very successful business by converting from conventional project management to scaled Agile.<br/> <br/>
      Excellent communicator. I pride myself on making sure people have the right information because it drives better results. Most business issues stem from poor communication, so I feel a responsibility to keep everyone on the same page. These skills helped increase my personal client retention rate by more than 40% in a year, and helped the team deliver 100% of our projects by the original deadline.<br/><br/>
      Results-oriented, constantly checking in with the goal to determine how close or how far away we are and what it will take to make it happen. I find this pressure inspiring and a great motivator for the rest of the team. In fact, over the past year, I was able to help my team shorten our average product time to market by two weeks.
      <br/><br/>
<strong>My responsibilities as a scrum master:</strong><br/>
•	Facilitate sprint planning, daily scrums, retrospectives, stakeholder meetings, and software demonstrations.<br/>
•	Protect PS team from outside distractions, impediments, or team conflicts, and maintain focus on product backlog project timeline.<br/>
•	Work closely with project owners in backlog management and continuous delivery of features.<br/>
•	Hence, the scrum master was expected to coach the teams accordingly keeping agile principles in mind and find innovative ways to smooth the learning curve.<br/>
•	I build strong and lasting relationships with Stakeholders for helping teams to deliver the right thing, at the right time.<br/>
•	Facilitate Scrum ceremonies such as stand-ups, retrospectives, story planning, and sprint planning. Acted as a facilitator for the Product Owner and the team both.<br/>
•	Removed impediments that were obstructing the team from achieving sprint goals, helped the team remain creative and productive while making sure its successes are visible to the Product Owner.<br/>
•	Educate and reinforce scrum methodology and agile framework to team members and stakeholders. Reporting and analysis of sprints.<br/>
•	Introduced and implemented Gherkin due to project needs. Customized the workflow and processes for the scrum teams.<br/>
•	Stakeholder management and show and tell the senior management.<br/>
•	Managing the finance carefully, estimation of any change request, forecasting and ensuring that the project estimates are managed upfront.<br/>

</p>
      
    </blockquote>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <strong><center>CERTIFICATIONS AND EDUCATION</center></strong>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><center>EMC Certified Network Storage SAN Specialist</br>
Microsoft Certified Professional: Microsoft Certified Systems Engineer ( MCSE )</br>
Project Management Professional ( PMP ), LinkedIn Learning</br>
Agile and Scrum Certified (PMI), Linkedln Learning</br>
Certified Scrum Master(CSM), Scrum Alliance</br>

Computer Technology, University of Illinois At Chicago
</p></center>
     
    </blockquote>
  </div>
</div>


	<center>
 <h1>My Resume!</h1>
 <p> </p>
 <img src="/assets/Capture.jpg" alt="PUSA-Icon" class="img-rounded" style="height: 300px;"/>
 
 <a href=""></a></br>
 <a href="http://www.linkedin.com/in/santo-derose-342ab39" target="new">Linkedin Profile!!</a>
</center>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sdrpmresume</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     
    <%= yield %>
  </body>
</html>